### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by sgspaddy** [cancerit/cgpVcf#24]
Hi, 
I was trying to install cgpVcf-2.0.1 on a Centos 6.6 machine.
It gave me the following errors:

gcc -g -O2 -I.  -fpic -c -o hfile_libcurl.pico hfile_libcurl.c
hfile_libcurl.c: In function ‘easy_errno’:
hfile_libcurl.c:93: error: ‘CURLE_NOT_BUILT_IN’ undeclared (first use in this function)
hfile_libcurl.c:93: error: (Each undeclared identifier is reported only once
hfile_libcurl.c:93: error: for each function it appears in.)
make[1]: *** [hfile_libcurl.pico] Error 1
make[1]: Leaving directory `/opt/cgpVcf-2.0.1/install_tmp/samtools/htslib-1.3'
make: *** [all-htslib] Error 2

Could you please help me solve these errors? Thank you very much!

Python: v2.6.6
Perl:      v5.10.1
gcc:      4.4.7

**Comment by ghost** [comment]
@sgspaddy Looks like this might be related https://github.com/pysam-developers/pysam/issues/249
Could you try a newer version of cgpVcf?

**Comment by sgspaddy** [comment]
@drjsanger Thank you very much. It fixed by  applying samtools/htslib@2805ae8.
